apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storage
  namespace: mysql
provisioner: kubernetes.io/no-provisioner

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1
  namespace: mysql
  labels:
    type: local
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data01
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-2
  namespace: mysql
  labels:
    type: local
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data02
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-3
  namespace: mysql
  labels:
    type: local
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data03
  persistentVolumeReclaimPolicy: Recycle

