apiVersion: v1
kind: Namespace
metadata:
  name: mysql

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
  namespace: mysql
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Service
metadata:
  labels:
    tier: backend
  name: mysql-service
  namespace: mysql
spec:
  type: NodePort
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30356
  selector:
    app: mysql
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: backend
  name: mysql
  namespace: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password
                key: MYSQL_ROOT_PASSWORD
          image: mysql:8.0
          name: mysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: mysql-volume
          hostPath:
            path: /tmp/data01
            type: DirectoryOrCreate
          # emptyDir: {} to reset sql directory everytime you pod restarted